/* Last Call Trivia — offline multiple-choice bank.
   c=category, d=difficulty(2 Hard,3 Expert,4 Fiendish), q=question, a=correct answer, w=[3 wrong]. */
window.LCT_BANK = [
/* FILM & TV */
{c:"film",d:2,q:"Which 1941 film, directed by and starring Orson Welles, opens with the whispered word 'Rosebud'?",a:"Citizen Kane",w:["Casablanca","The Maltese Falcon","Gone with the Wind"]},
{c:"film",d:2,q:"What was the first feature-length film to be entirely computer-animated?",a:"Toy Story",w:["Shrek","A Bug's Life","Antz"]},
{c:"film",d:2,q:"In 'Breaking Bad,' what is the name of Walter White's drug-dealer alter ego?",a:"Heisenberg",w:["Scarface","Capone","Maverick"]},
{c:"film",d:3,q:"Who directed 'Parasite,' the first non-English-language Best Picture winner?",a:"Bong Joon-ho",w:["Park Chan-wook","Hirokazu Kore-eda","Wong Kar-wai"]},
{c:"film",d:3,q:"Kurosawa's 'Seven Samurai' was remade as which 1960 Hollywood Western?",a:"The Magnificent Seven",w:["The Wild Bunch","A Fistful of Dollars","The Searchers"]},
{c:"film",d:3,q:"What 1927 film is widely considered the first major 'talkie'?",a:"The Jazz Singer",w:["Metropolis","Nosferatu","The Gold Rush"]},
{c:"film",d:3,q:"Which performer holds the record for most Academy Award acting nominations?",a:"Meryl Streep",w:["Katharine Hepburn","Bette Davis","Jack Nicholson"]},
{c:"film",d:2,q:"The HBO crime series 'The Wire' is set in which American city?",a:"Baltimore",w:["Philadelphia","Washington, D.C.","Newark"]},
{c:"film",d:4,q:"What fictional burger brand does Jules eat in the apartment scene of 'Pulp Fiction'?",a:"Big Kahuna Burger",w:["Krusty Burger","Wimpy","Bob's Burgers"]},
{c:"film",d:3,q:"In 'The Godfather,' the Corleones take their name from a town in which Italian region?",a:"Sicily",w:["Campania","Tuscany","Calabria"]},
/* MUSIC */
{c:"music",d:2,q:"Which composer wrote his Ninth Symphony while completely deaf?",a:"Ludwig van Beethoven",w:["Johann Sebastian Bach","Wolfgang Amadeus Mozart","Johannes Brahms"]},
{c:"music",d:2,q:"What is the best-selling album of all time?",a:"Thriller",w:["Back in Black","The Dark Side of the Moon","Rumours"]},
{c:"music",d:2,q:"Which Beatles album cover shows the band on a zebra crossing?",a:"Abbey Road",w:["Let It Be","Revolver","Rubber Soul"]},
{c:"music",d:4,q:"Which 20th-century American composer wrote the silent piece '4'33\"'?",a:"John Cage",w:["Philip Glass","Igor Stravinsky","Arnold Schoenberg"]},
{c:"music",d:3,q:"Who composed the four-opera 'Ring Cycle' (Der Ring des Nibelungen)?",a:"Richard Wagner",w:["Giuseppe Verdi","Richard Strauss","Gustav Mahler"]},
{c:"music",d:3,q:"In a standard orchestra, which instrument usually sounds the tuning note 'A'?",a:"The oboe",w:["The first violin","The clarinet","The flute"]},
{c:"music",d:3,q:"What musical term marks a gradual slowing of tempo?",a:"Ritardando",w:["Accelerando","Crescendo","Staccato"]},
{c:"music",d:2,q:"Which artist released the 2015 album 'To Pimp a Butterfly'?",a:"Kendrick Lamar",w:["Kanye West","J. Cole","Drake"]},
{c:"music",d:3,q:"Bob Dylan won the 2016 Nobel Prize in which category?",a:"Literature",w:["Peace","Physics","Chemistry"]},
{c:"music",d:4,q:"Which composer's unfinished 8th Symphony is nicknamed the 'Unfinished Symphony'?",a:"Franz Schubert",w:["Ludwig van Beethoven","Anton Bruckner","Antonin Dvorak"]},
/* VIDEO GAMES */
{c:"games",d:2,q:"What 1985 Nintendo platformer made a mustachioed plumber gaming's biggest mascot?",a:"Super Mario Bros.",w:["Donkey Kong","Sonic the Hedgehog","Mega Man"]},
{c:"games",d:3,q:"In 'Portal,' what is the name of the malevolent AI running Aperture Science?",a:"GLaDOS",w:["SHODAN","HAL 9000","Cortana"]},
{c:"games",d:2,q:"What 1972 Atari release was the first commercially successful arcade video game?",a:"Pong",w:["Space Invaders","Pac-Man","Asteroids"]},
{c:"games",d:4,q:"The 1983 video game crash is often blamed on a notoriously bad game based on which Spielberg film?",a:"E.T. the Extra-Terrestrial",w:["Pitfall","Space Invaders","Adventure"]},
{c:"games",d:3,q:"In 'The Witcher' series, what is the name of the monster-hunting protagonist?",a:"Geralt of Rivia",w:["Aragorn","Dandelion","Vesemir"]},
{c:"games",d:3,q:"Which puzzle game, created by Alexey Pajitnov in 1984, uses falling tetromino shapes?",a:"Tetris",w:["Columns","Dr. Mario","Bejeweled"]},
{c:"games",d:2,q:"What is the name of the bandana-wearing hero of the 'Metal Gear Solid' series?",a:"Solid Snake",w:["Sam Fisher","Nathan Drake","Master Chief"]},
{c:"games",d:4,q:"The Konami Code is up, up, down, down, left, right, left, right, and then which two buttons?",a:"B, A",w:["A, B","Start, Select","X, Y"]},
{c:"games",d:3,q:"In 'Among Us,' non-Impostor players are called what?",a:"Crewmates",w:["Survivors","Villagers","Civilians"]},
{c:"games",d:3,q:"What is the best-selling home video game console of all time?",a:"PlayStation 2",w:["Nintendo Wii","PlayStation 4","Xbox 360"]},
/* MYTHOLOGY */
{c:"myth",d:3,q:"In Norse myth, what is the name of the rainbow bridge connecting Midgard to Asgard?",a:"Bifrost",w:["Yggdrasil","Valhalla","Gjallarhorn"]},
{c:"myth",d:2,q:"Which Greek hero killed the Minotaur in the Labyrinth of Crete?",a:"Theseus",w:["Perseus","Heracles","Jason"]},
{c:"myth",d:3,q:"In Egyptian myth, which jackal-headed god presided over the dead?",a:"Anubis",w:["Horus","Ra","Set"]},
{c:"myth",d:2,q:"What is the name of Thor's hammer in Norse mythology?",a:"Mjolnir",w:["Gungnir","Gram","Hofund"]},
{c:"myth",d:3,q:"Achilles was made invulnerable by being dipped in which river of the underworld?",a:"The Styx",w:["The Lethe","The Acheron","The Cocytus"]},
{c:"myth",d:4,q:"In Hindu mythology, who is the elephant-headed god of beginnings?",a:"Ganesha",w:["Vishnu","Shiva","Hanuman"]},
{c:"myth",d:3,q:"What is the Norse name for the foretold final battle in which many gods die?",a:"Ragnarok",w:["Valhalla","Fimbulwinter","Yggdrasil"]},
{c:"myth",d:2,q:"Which three-headed dog guarded the entrance to the Greek underworld?",a:"Cerberus",w:["Orthrus","Fenrir","Argos"]},
{c:"myth",d:4,q:"Who is the hero of the Mesopotamian epic among the oldest known works of literature?",a:"Gilgamesh",w:["Enkidu","Hammurabi","Sargon"]},
{c:"myth",d:3,q:"In Roman myth, who is the counterpart of the Greek war god Ares?",a:"Mars",w:["Jupiter","Apollo","Vulcan"]},
/* SPACE */
{c:"space",d:3,q:"What is the name of the boundary around a black hole beyond which nothing can escape?",a:"The event horizon",w:["The singularity","The accretion disk","The photon sphere"]},
{c:"space",d:4,q:"What is the closest star to the Sun, about 4.24 light-years away?",a:"Proxima Centauri",w:["Alpha Centauri A","Barnard's Star","Sirius"]},
{c:"space",d:4,q:"Which astronomer formulated the three laws of planetary motion?",a:"Johannes Kepler",w:["Galileo Galilei","Isaac Newton","Nicolaus Copernicus"]},
{c:"space",d:4,q:"What is the term for a rapidly spinning collapsed star that emits regular pulses of radiation?",a:"A pulsar",w:["A quasar","A magnetar","A nova"]},
{c:"space",d:3,q:"Which planet rotates on its side, with an axial tilt of about 98 degrees?",a:"Uranus",w:["Neptune","Saturn","Venus"]},
{c:"space",d:4,q:"What is the name of the icy shell thought to be the source of long-period comets?",a:"The Oort Cloud",w:["The Kuiper Belt","The asteroid belt","The heliosphere"]},
{c:"space",d:3,q:"Who became the first human in outer space, in 1961?",a:"Yuri Gagarin",w:["Alan Shepard","Neil Armstrong","John Glenn"]},
{c:"space",d:3,q:"What is the most abundant element in the universe by mass?",a:"Hydrogen",w:["Helium","Oxygen","Carbon"]},
{c:"space",d:3,q:"Which 1977 spacecraft became the first human-made object to enter interstellar space?",a:"Voyager 1",w:["Voyager 2","Pioneer 10","New Horizons"]},
{c:"space",d:4,q:"What is the term for the point in an orbit where a planet is closest to the Sun?",a:"Perihelion",w:["Aphelion","Perigee","Apogee"]},
/* TECH & WEB */
{c:"tech",d:3,q:"Who is credited with inventing the World Wide Web in 1989?",a:"Tim Berners-Lee",w:["Vint Cerf","Bill Gates","Alan Turing"]},
{c:"tech",d:4,q:"Which 19th-century mathematician is often called the first computer programmer?",a:"Ada Lovelace",w:["Grace Hopper","Charles Babbage","Alan Turing"]},
{c:"tech",d:3,q:"Which programming language, released in 1991, is named after a British comedy troupe?",a:"Python",w:["Ruby","Java","Perl"]},
{c:"tech",d:4,q:"What is the term for a self-replicating program that spreads without needing a host file?",a:"A worm",w:["A trojan","A rootkit","Spyware"]},
{c:"tech",d:4,q:"The Turing Test assesses a machine's ability to do what?",a:"Seem indistinguishable from a human",w:["Process data quickly","Encrypt data securely","Store large amounts of data"]},
{c:"tech",d:2,q:"How many bits are in a byte?",a:"Eight",w:["Four","Sixteen","Two"]},
{c:"tech",d:4,q:"What 1969 US Department of Defense network is considered the precursor to the internet?",a:"ARPANET",w:["NSFNET","Ethernet","CompuServe"]},
{c:"tech",d:3,q:"Which cryptocurrency, introduced in 2009 by Satoshi Nakamoto, was the first decentralized digital currency?",a:"Bitcoin",w:["Ethereum","Litecoin","Dogecoin"]},
{c:"tech",d:3,q:"What does 'HTTP' stand for?",a:"HyperText Transfer Protocol",w:["HyperText Transmission Protocol","HighText Transfer Protocol","Hyperlink Transfer Procedure"]},
{c:"tech",d:4,q:"Which company developed the Android operating system before Google acquired it in 2005?",a:"Android Inc.",w:["Samsung","HTC","Nokia"]},
/* SCIENCE */
{c:"sci",d:3,q:"What is the only metal that is liquid at room temperature?",a:"Mercury",w:["Bromine","Gallium","Lead"]},
{c:"sci",d:3,q:"What is the most abundant gas in Earth's atmosphere?",a:"Nitrogen",w:["Oxygen","Carbon dioxide","Argon"]},
{c:"sci",d:2,q:"What is the hardest known naturally occurring material?",a:"Diamond",w:["Quartz","Titanium","Corundum"]},
{c:"sci",d:4,q:"What is the term for an animal active mainly at dawn and dusk?",a:"Crepuscular",w:["Nocturnal","Diurnal","Cathemeral"]},
{c:"sci",d:2,q:"What is the pH of a neutral solution at 25 degrees Celsius?",a:"7",w:["0","14","1"]},
{c:"sci",d:3,q:"What is the process by which a solid turns directly into a gas?",a:"Sublimation",w:["Evaporation","Condensation","Deposition"]},
{c:"sci",d:4,q:"Who arranged the periodic table by atomic weight in 1869?",a:"Dmitri Mendeleev",w:["Antoine Lavoisier","John Dalton","Marie Curie"]},
{c:"sci",d:2,q:"What is the largest organ of the human body?",a:"The skin",w:["The liver","The lungs","The brain"]},
{c:"sci",d:3,q:"What is the SI unit of electrical resistance?",a:"The ohm",w:["The volt","The ampere","The watt"]},
{c:"sci",d:4,q:"What is the study of fungi called?",a:"Mycology",w:["Botany","Entomology","Virology"]},
/* HISTORY */
{c:"hist",d:3,q:"Which empire, founded by Genghis Khan, became the largest contiguous land empire in history?",a:"The Mongol Empire",w:["The Ottoman Empire","The Persian Empire","The Qing Dynasty"]},
{c:"hist",d:3,q:"Which queen was the last active ruler of Ptolemaic Egypt?",a:"Cleopatra",w:["Nefertiti","Hatshepsut","Boudica"]},
{c:"hist",d:3,q:"The Magna Carta was sealed by which English king in 1215?",a:"King John",w:["Richard the Lionheart","Henry VIII","William the Conqueror"]},
{c:"hist",d:4,q:"Which two Roman cities were buried by the eruption of Mount Vesuvius in 79 AD?",a:"Pompeii and Herculaneum",w:["Athens and Sparta","Carthage and Utica","Troy and Mycenae"]},
{c:"hist",d:4,q:"Which 1919 treaty formally ended World War I?",a:"The Treaty of Versailles",w:["The Treaty of Westphalia","The Treaty of Tordesillas","The Yalta Agreement"]},
{c:"hist",d:3,q:"The French Revolution began in which year?",a:"1789",w:["1776","1804","1815"]},
{c:"hist",d:4,q:"Which Carthaginian general crossed the Alps with war elephants to attack Rome?",a:"Hannibal",w:["Julius Caesar","Scipio Africanus","Spartacus"]},
{c:"hist",d:4,q:"The Rosetta Stone was key to deciphering which ancient writing system?",a:"Egyptian hieroglyphs",w:["Sumerian cuneiform","Linear B","Mayan glyphs"]},
{c:"hist",d:4,q:"Which Russian royal family was executed in 1918?",a:"The Romanovs",w:["The Habsburgs","The Bourbons","The Tudors"]},
{c:"hist",d:4,q:"The Black Death of the 14th century was primarily which disease?",a:"Bubonic plague",w:["Cholera","Smallpox","Typhoid"]},
/* GEOGRAPHY */
{c:"geo",d:3,q:"What is the capital of Australia?",a:"Canberra",w:["Sydney","Melbourne","Perth"]},
{c:"geo",d:4,q:"Which African country has more pyramids than Egypt?",a:"Sudan",w:["Mexico","Ethiopia","Libya"]},
{c:"geo",d:3,q:"What is the smallest country in the world by area?",a:"Vatican City",w:["Monaco","San Marino","Liechtenstein"]},
{c:"geo",d:3,q:"Mount Everest sits on the border between Nepal and which other country?",a:"China",w:["India","Bhutan","Pakistan"]},
{c:"geo",d:4,q:"The Atacama Desert, one of the driest places on Earth, lies mainly in which country?",a:"Chile",w:["Peru","Argentina","Bolivia"]},
{c:"geo",d:4,q:"Lake Baikal, the world's deepest freshwater lake, is in which country?",a:"Russia",w:["Canada","Tanzania","Mongolia"]},
{c:"geo",d:3,q:"Which mountain range is traditionally said to divide Europe from Asia?",a:"The Ural Mountains",w:["The Alps","The Carpathians","The Pyrenees"]},
{c:"geo",d:4,q:"Which country has the longest coastline in the world?",a:"Canada",w:["Russia","Indonesia","Australia"]},
{c:"geo",d:4,q:"What is the capital of New Zealand?",a:"Wellington",w:["Auckland","Christchurch","Queenstown"]},
{c:"geo",d:3,q:"What is the capital of Brazil?",a:"Brasilia",w:["Rio de Janeiro","Sao Paulo","Salvador"]},
/* LITERATURE */
{c:"lit",d:3,q:"Which Russian author wrote 'War and Peace'?",a:"Leo Tolstoy",w:["Fyodor Dostoevsky","Anton Chekhov","Ivan Turgenev"]},
{c:"lit",d:2,q:"Who wrote the dystopian novel '1984'?",a:"George Orwell",w:["Aldous Huxley","Ray Bradbury","H.G. Wells"]},
{c:"lit",d:3,q:"The Iliad and the Odyssey are attributed to which ancient Greek poet?",a:"Homer",w:["Virgil","Sophocles","Ovid"]},
{c:"lit",d:4,q:"What is the term for a word that reads the same forwards and backwards?",a:"A palindrome",w:["An anagram","A homonym","A palinode"]},
{c:"lit",d:4,q:"Who wrote 'One Hundred Years of Solitude'?",a:"Gabriel Garcia Marquez",w:["Jorge Luis Borges","Pablo Neruda","Mario Vargas Llosa"]},
{c:"lit",d:4,q:"Which Norwegian playwright wrote 'A Doll's House'?",a:"Henrik Ibsen",w:["August Strindberg","Anton Chekhov","Oscar Wilde"]},
{c:"lit",d:3,q:"What is a word made by rearranging the letters of another called?",a:"An anagram",w:["A palindrome","An acronym","A synonym"]},
{c:"lit",d:3,q:"Who created the Belgian detective Hercule Poirot?",a:"Agatha Christie",w:["Arthur Conan Doyle","Dorothy L. Sayers","P.D. James"]},
{c:"lit",d:3,q:"Which American writer wrote the poem 'The Raven'?",a:"Edgar Allan Poe",w:["Walt Whitman","Emily Dickinson","Robert Frost"]},
{c:"lit",d:4,q:"Who wrote 'The Divine Comedy'?",a:"Dante Alighieri",w:["Petrarch","Boccaccio","Geoffrey Chaucer"]},
/* ART */
{c:"art",d:3,q:"Which Dutch post-Impressionist painted 'The Starry Night'?",a:"Vincent van Gogh",w:["Claude Monet","Paul Cezanne","Paul Gauguin"]},
{c:"art",d:3,q:"The Sistine Chapel ceiling was painted by which Renaissance master?",a:"Michelangelo",w:["Leonardo da Vinci","Raphael","Donatello"]},
{c:"art",d:4,q:"Which art movement, pioneered by Picasso and Braque, fractured subjects into geometric viewpoints?",a:"Cubism",w:["Surrealism","Futurism","Fauvism"]},
{c:"art",d:3,q:"Who painted 'The Persistence of Memory,' famous for its melting clocks?",a:"Salvador Dali",w:["Rene Magritte","Max Ernst","Joan Miro"]},
{c:"art",d:4,q:"Which architect designed Fallingwater and New York's Guggenheim Museum?",a:"Frank Lloyd Wright",w:["Le Corbusier","Mies van der Rohe","Frank Gehry"]},
{c:"art",d:3,q:"Which Norwegian artist painted 'The Scream'?",a:"Edvard Munch",w:["Gustav Klimt","Egon Schiele","James Ensor"]},
{c:"art",d:4,q:"The simplest of the three classical Greek column orders is which one?",a:"Doric",w:["Ionic","Corinthian","Tuscan"]},
{c:"art",d:4,q:"Which Mexican artist is known for her self-portraits and marriage to Diego Rivera?",a:"Frida Kahlo",w:["Georgia O'Keeffe","Tamara de Lempicka","Remedios Varo"]},
{c:"art",d:4,q:"Andy Warhol was a leading figure of which 1960s art movement?",a:"Pop Art",w:["Abstract Expressionism","Minimalism","Dadaism"]},
{c:"art",d:4,q:"What is the technique of painting onto freshly laid wet plaster called?",a:"Fresco",w:["Tempera","Gouache","Encaustic"]},
/* FOOD & BEER */
{c:"food",d:3,q:"Which beer style was historically brewed extra-hoppy to survive the voyage to India?",a:"IPA",w:["Pilsner","Porter","Saison"]},
{c:"food",d:4,q:"The flower of which climbing plant gives beer its bitterness and aroma?",a:"Hops",w:["Barley","Hibiscus","Chamomile"]},
{c:"food",d:3,q:"What gas, produced by yeast during fermentation, carbonates beer?",a:"Carbon dioxide",w:["Nitrogen","Oxygen","Hydrogen"]},
{c:"food",d:3,q:"Lager and ale are distinguished mainly by the type of what?",a:"Yeast",w:["Hops","Water","Malt"]},
{c:"food",d:4,q:"What does 'ABV' on a beer label stand for?",a:"Alcohol By Volume",w:["Alcohol By Weight","Average Beer Value","Alcohol Base Value"]},
{c:"food",d:3,q:"Champagne can legally bear that name only if it comes from a region of which country?",a:"France",w:["Italy","Spain","Belgium"]},
{c:"food",d:4,q:"Which country leads the world in beer consumption per capita?",a:"The Czech Republic",w:["Germany","Ireland","Belgium"]},
{c:"food",d:3,q:"Sake, the traditional Japanese beverage, is brewed from what?",a:"Rice",w:["Barley","Wheat","Potato"]},
{c:"food",d:4,q:"The Scoville scale measures what property of food?",a:"Spiciness",w:["Sweetness","Acidity","Saltiness"]},
{c:"food",d:3,q:"Which dark, roasted beer style is most associated with Guinness?",a:"Stout",w:["Pilsner","Pale ale","Wheat beer"]},
/* SPORTS */
{c:"sport",d:3,q:"Which country has won the most men's FIFA World Cup titles?",a:"Brazil",w:["Germany","Italy","Argentina"]},
{c:"sport",d:3,q:"The modern Olympic Games were revived in 1896 in which city?",a:"Athens",w:["Paris","London","Rome"]},
{c:"sport",d:3,q:"In tennis, what term denotes a score of zero?",a:"Love",w:["Nil","Deuce","Fault"]},
{c:"sport",d:3,q:"Which boxer was known as 'The Greatest'?",a:"Muhammad Ali",w:["Mike Tyson","Joe Frazier","Sugar Ray Robinson"]},
{c:"sport",d:4,q:"In golf, what is one stroke under par on a hole called?",a:"A birdie",w:["An eagle","A bogey","A par"]},
{c:"sport",d:4,q:"In which country did the sport of table tennis originate?",a:"England",w:["China","Japan","United States"]},
{c:"sport",d:4,q:"In cricket, taking three wickets in three consecutive deliveries is called what?",a:"A hat-trick",w:["A maiden","A century","A googly"]},
{c:"sport",d:4,q:"Which swimmer won eight gold medals at the 2008 Beijing Olympics?",a:"Michael Phelps",w:["Mark Spitz","Ian Thorpe","Caeleb Dressel"]},
{c:"sport",d:3,q:"For which sport is the Stanley Cup the championship trophy?",a:"Ice hockey",w:["Basketball","Baseball","American football"]},
{c:"sport",d:4,q:"The martial art of Judo originated in which country?",a:"Japan",w:["China","Korea","Brazil"]},
/* ODD & GENERAL */
{c:"world",d:4,q:"What is the only letter that does not appear in any U.S. state name?",a:"Q",w:["Z","X","J"]},
{c:"world",d:3,q:"Which language has the most native (first-language) speakers in the world?",a:"Mandarin Chinese",w:["English","Spanish","Hindi"]},
{c:"world",d:3,q:"A 'baker's dozen' equals how many?",a:"Thirteen",w:["Twelve","Fourteen","Eleven"]},
{c:"world",d:4,q:"What is the collective noun for a group of crows?",a:"A murder",w:["A flock","A gaggle","A pod"]},
{c:"world",d:4,q:"In the NATO phonetic alphabet, which word stands for the letter 'R'?",a:"Romeo",w:["Roger","Rex","Rocky"]},
{c:"world",d:3,q:"What is the only mammal capable of true sustained flight?",a:"The bat",w:["The flying squirrel","The colugo","The sugar glider"]},
{c:"world",d:4,q:"How many hearts does an octopus have?",a:"Three",w:["One","Two","Four"]},
{c:"world",d:4,q:"Which is the only English number whose letters equal its value?",a:"Four",w:["Three","Five","Six"]},
{c:"world",d:3,q:"What is the chemical name for common table salt?",a:"Sodium chloride",w:["Sodium bicarbonate","Potassium chloride","Calcium carbonate"]},
{c:"world",d:3,q:"Which country gifted the Statue of Liberty to the United States?",a:"France",w:["Britain","Spain","Italy"]}
];
